[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"

# Use the Netlify Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Configure the plugin
[plugins.inputs]
  # Disable runtime as we're doing static export
  useRuntime = false

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200