import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  keywords: "Next.js, React, Web Development, SEO",
  author: "Geaux Specialist LLC",
  robots: "index, follow",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Organization",
              "name": "Geaux Specialist LLC",
              "url": "https://geauxspecialist.com",
              "logo": "https://geauxspecialist.com/logo.png",
              "sameAs": [
                "https://www.facebook.com/geauxspecialist",
                "https://www.twitter.com/geauxspecialist",
                "https://www.linkedin.com/company/geauxspecialist"
              ]
            })
          }}
        />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
