# .github/workflows/stale.yml
name: Stale Issues and PRs

on:
  schedule:
    - cron: '0 8 * * 1' # Run every Monday at 8:00 AM UTC

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v7
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
          # Settings for stale issues
          stale-issue-message: 'This issue has been automatically marked as stale because it has not had recent activity. It will be closed in 14 days if no further activity occurs.'
          close-issue-message: 'This issue has been automatically closed due to inactivity. Feel free to reopen it if you believe it still requires attention.'
          days-before-issue-stale: 60
          days-before-issue-close: 14
          exempt-issue-labels: 'pinned,security,bug,enhancement,in-progress'
          
          # Settings for stale PRs
          stale-pr-message: 'This pull request has been automatically marked as stale because it has not had recent activity. It will be closed in 14 days if no further activity occurs.'
          close-pr-message: 'This pull request has been automatically closed due to inactivity. Feel free to reopen it if you want to continue working on it.'
          days-before-pr-stale: 30
          days-before-pr-close: 14
          exempt-pr-labels: 'pinned,security,in-progress,awaiting-review'
          
          # Additional settings
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          exempt-all-milestones: true
          operations-per-run: 100